CREATE TABLE IF NOT EXISTS EMPLOYEE(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	DEPARTMENT TEXT NOT NULL,
	CREATION_DATE TEXT NOT NULL,
	MODIFICATION_DATE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ROOM(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	CAPACITY INTEGER NOT NULL,
	LOCATION TEXT NOT NULL,
	CREATION_DATE TEXT NOT NULL,
	MODIFICATION_DATE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVATION(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ID_EMPLOYEE INTEGER NOT NULL,
	ID_ROOM INTERGER NOT NULL,
	CREATION_DATE TEXT NOT NULL,
	MODIFICATION_DATE TEXT NOT NULL,
	FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE(ID),
	FOREIGN KEY (ID_ROOM) REFERENCES ROOM(ID)
);

